export const inventory = {
    createProductButton: "//a[contains(@href, 'customer_products/new')]",
    searchProductField: "input[placeholder='Search by product name']",
    elipsisInventoryPage: "//tbody//tr[1]//td[9]",
    editInventoryOption: "//tbody//tr[1]//td[9]//ul//li[1]",
    deleteInventoryOption: "//tbody//tr[1]//td[9]//ul//li[2]",
    confirmDeleteInventoryButton: "//*[@id='__nuxt']/div/main/div/section/div/div/div/div[3]/div[4]/div[2]/div/footer/div[2]/button",
    firstProductInventoryPage: "tbody tr:first-of-type td:nth-of-type(2) div div div",
    productTitleUpdate: "[placeholder='e.g. Sendoso socks']",
    saveAndCloseButton: "html > body > div:nth-of-type(2) > main > div:nth-of-type(2) > div:nth-of-type(2) > div > div:nth-of-type(7) > div:nth-of-type(2) > button",
    saveChangesButton: "/html/body/div[2]/main/div[2]/div[2]/div/div[11]/div/div/div/div/footer/div/div/div[2]/button",
    nextButton: "//button[@id=\"product_step_button\"]",
    productNameField: "#product_name",
    uploadImage: "#product_images_attributes_0_pic",
    closePopUp: "#close > div > div > div.modal-footer.close-modal-footer > button",
    warehouseDropdown: "#product_warehouse_ids_",
    successMessage: ".swal2-content",
    productName: "//input[@id='product_name']",
    btnNextNew: "[class^='footerContainer'] div:nth-child(2) button",
    addProductTitle: "form[data-testid='product-details-form'] div:nth-child(1) div:nth-child(1) div:nth-child(1) input[type='text']:nth-child(2)",
    addProductCost: "form[data-testid='product-details-form'] div:nth-child(4) input",
    addProductVendor: "form[data-testid='product-details-form'] div:nth-child(2) input",
    addProductBrand: "form[data-testid='product-details-form'] div:nth-child(3) input",
    singleVariant: "div[data-testid='product-variations'] div:nth-child(2) button",
    multipleVariant: "div[data-testid='product-variations'] div:nth-child(1) button",
    sizeMenu: "[id='size'] button:nth-child(2)",
    materialMenu: "[id='material'] button:nth-child(2)",
    genderMenu: "[id='gender'] button:nth-child(2)",
    colorMenu: "[id='color'] button:nth-child(2)",
    numberOfItems: "input[type='number']",
    warehouseMenu: "//span[contains(text(), 'Select warehouse')]",
    domesticShipping: "div[class^='stl-form__radio']:nth-child(1)",
    marketingTeam: "[class='TableContainer'] tr:nth-child(1) td:nth-child(1)",
    SDRs: "[class='TableContainer'] tr:nth-child(2) td:nth-child(1)",
    AEs: "[class='TableContainer'] tr:nth-child(3) td:nth-child(1)",
    successPopup: "[class='swal2-confirm swal2-styled']",
    createShipNoticeButton: "//*[@id='__nuxt']/div/main/div/section/div/div/div/div[1]/div/div[3]/div/button",
    enterProductNameField: "//*[@placeholder='Enter product name']",
    saveShipNoticeButton: "//button[@type='button'][text()=' Save']",
    closeSuccessShipNoticeModal: "//*[@id='__nuxt']/div/main/div/div[2]/div[2]/div/footer/div[1]/button",
    snStatus: "//*[@class='table-fixed min-w-full']//tbody//tr[1]//td[7]//span",
    clearSearchShipNoticeModal: "//*[@class='grid items-center justify-between gap-x-2 mx-1 my-2']//button[@aria-label]",
    continueEditingOption: "[class*='items-end'] div:nth-child(2) button",
    printingName: "[id='product_name']",
    successDialogClose: "[class*='popup'] button:nth-child(1)",
    saveBtn: "[class='btn next-step save-button']",
    getProductName: "table[class] tbody tr:nth-child(1) td:nth-child(2) div div div",
    printOnDemandSuccess: "Your product is created! It should be available for sending shortly!",
    successDialogMessage: "[class*='popup'] div div:nth-child(2)",
    nextStepBtn: "[class='btn next-step']",
}
