export const marketplace = {
    senditNowButton: "//button[text()=' Send it now']",
    confirmRecipientToggleButton: "(//span[contains(@class,'oso-rounded-full')])[1]",
    name: "input[name='name']",
    address: "input[name='address']",
    city: "input[name='city']",
    zip: "input[name='zip']",
    email: "input[name='email']",
    notes: "textarea[name='noteCardInput']",
    sendIt:"button[type='submit']",
    countryDropdown:"button[id*='headlessui-listbox']",
    countryValue:"//li[text()='United States']",
    continueButton:"//button[text()=' Continue']",
    nextButton:"//button[text()=' Next']",
    AddressIsCorrectBtn:"//li//span[normalize-space(.)='Address is correct']",
    firstName:"input[name='firstName']",
    lastName:"input[name='lastName']",
    streetAddress:"#recipient-address",
    selectSomethingElseButton:"//button[text()=' Select something else']",
    peepCookies:"//a[text()='TEST - Sec Mug']",
    selectThisGiftButton:"//button[text()=' Select this Gift']",
    acceptYourGiftButton:"//button[text()=' Accept your gift']",
    submitButton:"button[type=\"submit\"]",
    state:"//label[text()='State']",
    subject:"Choose your gift from touch send at sendoso",
    confirmChoiceButton:"//button[text()=' Confirm Choice']"
}
